name: MYSql Dump Playbook
on: [push]

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute Sample Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Execute Playbook Action Step
        id: Execution
        uses: ./
        with:
          database_host: ${{ secrets.DB_HOST }}
          database_username: ${{ secrets.DB_USERNAME }}
          database_password: ${{ secrets.DB_PASSWORD }}
          database_port: "3306"
          database_name: ${{ secrets.DB_NAME }}
          dumpfile_name: "database"
          dumpfile_path: "backup"